//! Golden-vector tests: the Rust implementation must reproduce the frozen
//! vectors under `spec/vectors/`, which were generated by independent Python
//! implementations (see `xcheck/`).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::fs;
use std::path::PathBuf;

use ed25519_dalek::{SigningKey, VerifyingKey};
use serde_json::Value;

fn vectors_dir(family: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../spec/vectors")
        .join(family)
}

fn load_family(family: &str) -> Vec<Value> {
    let dir = vectors_dir(family);
    let mut cases = Vec::new();
    for entry in fs::read_dir(&dir).unwrap_or_else(|e| panic!("missing {dir:?}: {e}")) {
        let path = entry.unwrap().path();
        if path.extension().is_some_and(|e| e == "json") {
            let text = fs::read_to_string(&path).unwrap();
            cases.push(serde_json::from_str(&text).unwrap());
        }
    }
    assert!(!cases.is_empty(), "no vectors found in {dir:?}");
    cases
}

#[test]
fn jcs_vectors() {
    for case in load_family("jcs") {
        let name = case["name"].as_str().unwrap();
        let value = &case["input"]["value"];
        let expected = case["expected"]["canonical"].as_str().unwrap();
        let expected_sha = case["expected"]["sha256_hex"].as_str().unwrap();

        let canonical = axon_ext::jcs::canonical_bytes(value)
            .unwrap_or_else(|e| panic!("{name}: canonicalization failed: {e}"));
        assert_eq!(
            String::from_utf8(canonical.clone()).unwrap(),
            expected,
            "{name}: canonical bytes differ"
        );
        let digest = axon_ext::jcs::canonical_sha256(value).unwrap();
        assert_eq!(hex::encode(digest), expected_sha, "{name}: digest differs");
    }
}

#[test]
fn dsse_vectors() {
    for case in load_family("dsse") {
        let name = case["name"].as_str().unwrap();
        let input = &case["input"];
        let expected = &case["expected"];

        let payload_type = input["payload_type"].as_str().unwrap();
        let payload = input["payload_utf8"].as_str().unwrap().as_bytes();
        let sk_bytes: [u8; 32] = hex::decode(input["private_key_hex"].as_str().unwrap())
            .unwrap()
            .try_into()
            .unwrap();
        let pk_bytes: [u8; 32] = hex::decode(input["public_key_hex"].as_str().unwrap())
            .unwrap()
            .try_into()
            .unwrap();
        let signing_key = SigningKey::from_bytes(&sk_bytes);
        let verifying_key = VerifyingKey::from_bytes(&pk_bytes).unwrap();
        assert_eq!(
            signing_key.verifying_key(),
            verifying_key,
            "{name}: key pair mismatch"
        );

        // PAE construction matches.
        let pae = axon_ext::dsse::pae(payload_type, payload);
        assert_eq!(
            String::from_utf8(pae).unwrap(),
            expected["pae_utf8"].as_str().unwrap(),
            "{name}: PAE differs"
        );

        // keyid is the RFC 7638 thumbprint of the signer.
        let keyid = axon_crypto::jwk::thumbprint(&verifying_key);
        assert_eq!(
            keyid,
            expected["keyid"].as_str().unwrap(),
            "{name}: keyid differs"
        );

        // Deterministic Ed25519: signing reproduces the frozen envelope.
        let envelope = axon_ext::dsse::sign(payload_type, payload, &keyid, &signing_key);
        assert_eq!(
            envelope.payload,
            expected["payload_base64"].as_str().unwrap(),
            "{name}: payload encoding differs"
        );
        assert_eq!(
            envelope.signatures[0].sig,
            expected["sig_base64"].as_str().unwrap(),
            "{name}: signature differs"
        );

        // And the frozen envelope verifies.
        let recovered =
            axon_ext::dsse::verify(&envelope, payload_type, &keyid, &verifying_key).unwrap();
        assert_eq!(recovered, payload, "{name}: verified payload differs");
    }
}
